version: '3'

services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    image: "{{ cookiecutter.__project_slug }}"
    container_name: "{{ cookiecutter.__project_slug }}_cn"
    restart: unless-stopped
