name: integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "**"
  release:
    branches:
      - main
    types:
      - created

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        uses: Foxon-Consulting/github-actions/integration/common/pre-commit@main

  integration:
    uses: Foxon-Consulting/github-actions/.github/workflows/nextjs_integration.yml@main
    with: # passing this as inputs to
      artifact-name: "{{cookiecutter.__artifact_name_formatted}}"
      deploy-image-name: "s"

  # releasing:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - pre-commit
  #     - integration
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: releasing
  #       uses: Foxon-Consulting/github-actions/delivery/common/release-please@main

  delivery:
    needs:
      # - releasingg
      - integration
    permissions:
      contents: write
      pull-requests: write
    uses: Foxon-Consulting/github-actions/.github/workflows/nextjs_delivery.yml@main
    with:
      deploy-image-name: "{{cookiecutter.__deploy_image_name_formatted}}"
    secrets:
      docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker-password: ${{ secrets.DOCKERHUB_TOKEN }}

  deployment:
    needs:
      # - releasing
      - delivery
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      pull-requests: write
    uses: Foxon-Consulting/github-actions/.github/workflows/simple_deployment.yml@main
