version: '3'

services:
  devops-toolkit:
    image: devops_toolkit
    ports:
      - "{{ cookiecutter.port }}:22"
    volumes:
      - ./:/home/user/{{ cookiecutter.__project_slug }}
      - ./key:/home/user/key
      - ~/.aws:/root/.aws
    container_name: "{{ cookiecutter.__module_name_formatted }}_cn"
    restart: unless-stopped
