# simulates deployment by k8s
version: "3"

services:
  nextjs-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: "{{cookiecutter.__project_slug}}_cn"
    restart: unless-stopped
    stdin_open: true
