version: "3"

services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile
    image: "{{ cookiecutter.__project_slug }}"
    ports:
      - "3000:80"
    container_name: "{{cookiecutter.__project_slug}}_cn"
    restart: unless-stopped
    stdin_open: true
