version: "3"

services:
  node-toolkit:
    image: foxonconsulting/node-toolkit:1.0.1
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./:/{{ cookiecutter.__project_slug }}
    ports:
      - "3000:3000"
    container_name: "{{ cookiecutter.__project_slug }}-toolkit_cn"
    restart: unless-stopped
    stdin_open: true
